packages:
  - "."
allowBuilds:
  '@prisma/engines': true
  '@stripe/cli': true
  core-js: set this to true or false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
